### ISSUE TITLE
OpenVPN config

### ISSUE THREAD

**Issue by Atlanta** [crestic-urca/remotelabz-docs#6]
**OS :** Ubuntu 18.04

Installed `openvpn` and `easy-rsa` packages. Some steps are wrong when configuring OpenVPN : 

> Edit the file openssl-easyrsa.cnf
>
> sudo nano /usr/share/easy-rsa/openssl-easyrsa.cnf
> 
> and comment the line beginning with RANDFILE
>
> #RANDFILE               = $ENV::EASYRSA_PKI/.rnd

The specified file does not exists.

> sudo ./easyrsa init-pki
> sudo ./easyrsa build-ca

Commands does not exists in /usr/share/easy-rsa.

The rest is not very clear as well.

**Comment by Atlanta** [comment]
`easyrsa` requires >= 3.0 for `easy-rsa` package, which is only available starting Ubuntu 20.04, therefore we shouldn't be using this solution.

Even the official OpenSSL server tutorial is using old commands, but seems way more clear:
https://openvpn.net/community-resources/setting-up-your-own-certificate-authority-ca/

**Comment by florent-n** [comment]
Maintenance of 2 distributions is too difficult and I prefer to work only on Ubuntu 20

**Comment by Atlanta** [comment]
Then we should tell people not to use `apt-get` to get easy-rsa but get it from GitHub instead. Ubuntu 18.04 users can get EasyRSA 3 here:
https://github.com/OpenVPN/easy-rsa/releases

In addition not to be platform-dependant, it allows users to generate server CA and other stuff without the require to use `sudo` because you do not have to execute this command in a system folder. The procedure is simply the following (just tested on Ubuntu 18.04):

```sh
cd ~
# link to the latest version
wget https://github.com/OpenVPN/easy-rsa/releases/download/v3.0.8/EasyRSA-3.0.8.tgz
tar -xzf EasyRSA-3.0.8.tgz
cd EasyRSA-3.0.8

# easyrsa commands and vars file config goes here
```

All other commands seems to work correctly starting from here.
